_wandb:
    value:
        cli_version: 0.21.3
        e:
            fershvfbnl4hxmmmfivnz4hteum37x76:
                apple:
                    ecpuCores: 2
                    gpuCores: 24
                    memoryGb: 32
                    name: Apple M1 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "2147483648"
                args:
                    - --input_artifact
                    - sample.csv:latest
                    - --output_artifact
                    - clean_sample.csv
                    - --output_type
                    - clean_data
                    - --output_description
                    - Cleaned data
                    - --min_price
                    - "10"
                    - --max_price
                    - "350"
                codePath: src/basic_cleaning/run.py
                codePathLocal: run.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "105293537280"
                email: aliafzal9323@gmail.com
                executable: /opt/miniconda3/envs/mlflow-b3f4da2f31f0dce3528153405a30c78d50a39ae3/bin/python
                git:
                    commit: f5f3081bd51bdd2ed67b914456df6e044bd16d34
                    remote: https://github.com/Anshuman5/mlops_assessment4.git
                host: MacBookPro
                memory:
                    total: "34359738368"
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/aliafzal/Dev/mlops_assesment_new/mlops_assessment4/src/basic_cleaning/run.py
                python: CPython 3.13.11
                root: /Users/aliafzal/Dev/mlops_assesment_new/mlops_assessment4/src/basic_cleaning
                startedAt: "2026-01-13T18:32:22.574118Z"
                writerId: fershvfbnl4hxmmmfivnz4hteum37x76
        m: []
        python_version: 3.13.11
        t:
            "3":
                - 2
            "4": 3.13.11
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
input_artifact:
    value: sample.csv:latest
max_price:
    value: 350
min_price:
    value: 10
output_artifact:
    value: clean_sample.csv
output_description:
    value: Cleaned data
output_type:
    value: clean_data
