_wandb:
    value:
        cli_version: 0.21.3
        e:
            t986tqlhdvi0o41k4o5cfgscbl9he6de:
                apple:
                    ecpuCores: 2
                    gpuCores: 24
                    memoryGb: 32
                    name: Apple M1 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "2147483648"
                args:
                    - clean_sample.csv:latest
                    - "0.2"
                    - --random_seed
                    - "42"
                    - --stratify_by
                    - neighbourhood_group
                codePath: components/train_val_test_split/run.py
                codePathLocal: run.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "105328283648"
                email: aliafzal9323@gmail.com
                executable: /opt/miniconda3/envs/mlflow-9e90f5fe2c8b525335212978234fa75adebb4614/bin/python
                git:
                    commit: c02b79a061b4741c44c6445a7b5d257af1fc2028
                    remote: https://github.com/devpassive/mlops_assessment4.git
                host: MacBookPro
                memory:
                    total: "34359738368"
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/aliafzal/Dev/mlops_assesment_new/mlops_assessment4/components/train_val_test_split/run.py
                python: CPython 3.13.11
                root: /Users/aliafzal/Dev/mlops_assesment_new/mlops_assessment4/components/train_val_test_split
                startedAt: "2026-01-13T18:55:38.460760Z"
                writerId: t986tqlhdvi0o41k4o5cfgscbl9he6de
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.11
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
input:
    value: clean_sample.csv:latest
random_seed:
    value: 42
stratify_by:
    value: neighbourhood_group
test_size:
    value: 0.2
